import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createHash } from 'node:crypto';
const bytes = fs.readFileSync(new URL('./arcmira-source-shortlist.n8n.json', import.meta.url));
const w = JSON.parse(bytes);
const proof = JSON.parse(fs.readFileSync(new URL('./verification.json', import.meta.url)));
assert.equal(createHash('sha256').update(bytes).digest('hex'), proof.distributed_workflow_sha256);
assert.equal(w.active, false);
assert.deepEqual(Object.keys(w).sort(), ['active', 'connections', 'name', 'nodes', 'settings']);
assert.equal(w.nodes.length, 4);
const http = w.nodes.find(n => n.name === 'Search Arcmira');
assert.equal(http.type, 'n8n-nodes-base.httpRequest');
assert.equal(http.parameters.method, 'GET');
assert.equal(http.parameters.url, 'https://api.arcmira.com/v1/search');
assert.equal(http.parameters.authentication, 'genericCredentialType');
assert.equal(http.parameters.genericAuthType, 'httpBearerAuth');
assert.deepEqual(http.credentials, {});
assert.equal(http.retryOnFail, false);
assert.equal(http.parameters.options.redirect.redirect.followRedirects, false);
assert.deepEqual(http.parameters.queryParameters.parameters.map(x => x.name), ['q', 'after', 'before', 'limit']);
assert.equal(http.parameters.queryParameters.parameters.at(-1).value, '3');
assert.equal(w.nodes.filter(n => n.type === 'n8n-nodes-base.httpRequest').length, 1);
assert.ok(!/(arc_sk_[A-Za-z0-9]+|resumeToken|executionData|\/Users\/|webhookId|instanceId|credentialId)/.test(bytes.toString()));
assert.ok(w.nodes.every(n => !n.credentials || Object.keys(n.credentials).length === 0));
assert.ok(!http.parameters.options.pagination);
console.log('PASS: unchanged workflow digest, empty credential binding, one fixed-limit GET, no execution state or known credential patterns. No network requests.');
