const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const { createHash } = require('node:crypto');
const assert = require('node:assert/strict');
const packed = JSON.parse(fs.readFileSync('pack.json'))[0];
const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'arcmira-activepieces-packed-'));
execFileSync('tar', ['-xzf', path.resolve(packed.filename), '-C', directory]);
const manifest = JSON.parse(fs.readFileSync(path.join(directory, 'package/package.json')));
assert.deepEqual(manifest.dependencies, {});
assert.equal(manifest.private, undefined);
assert.ok(fs.statSync(path.join(directory, 'package/THIRD_PARTY_LICENSES.txt')).size > 1000);
const script = `const assert=require('node:assert/strict'); const Module=require('node:module'); const original=Module._load; Module._load=function(id,...args){ if(!id.startsWith('./')&&!id.startsWith('node:')&&!Module.builtinModules.includes(id)) throw Error('External dependency: '+id); return original.call(this,id,...args); }; const {arcmira}=require('./package'); assert.equal(arcmira.displayName,'Arcmira: YouTube Transcript Search'); let calls=0; global.fetch=async()=>{calls++;return Response.json({chunks:[],partial:false});}; arcmira.getAction('search_transcripts').run({auth:{secret_text:'fixture'},propsValue:{query:'coding agents',limit:1}}).then(x=>{assert.deepEqual(x,{chunks:[],partial:false}); assert.equal(calls,1);console.log('Packed piece loads and runs with external package imports blocked.');}).catch(e=>{console.error(e);process.exitCode=1;});`;
fs.writeFileSync(path.join(directory, 'check.cjs'), script);
const result = execFileSync(process.execPath, ['check.cjs'], { cwd: directory, encoding: 'utf8' });
fs.writeFileSync('isolated-package-check.txt', result);
fs.writeFileSync('package-verification.json', JSON.stringify({checkedAt:new Date().toISOString(),archive:packed.filename,sha256:createHash('sha256').update(fs.readFileSync(packed.filename)).digest('hex'),bytes:packed.size,files:packed.files.map(file=>file.path),externalRuntimeDependencies:0,isolatedActionPassed:true,hostInstallationVerified:false,published:false},null,2)+'\n');
console.log(result);
